baseURL = 'https://Lassenwirdas.github.io/'
languageCode = 'en-us'
title = 'Lasse Medla Web-Page'
[markup.highlight]
noclasses = false

[[module.imports]]
path = "github.com/willfaught/paige"
[caches]
  [caches.images]
    dir = ':cacheDir/images'