baseURL = 'https://Lassenwirdas.github.io/'
languageCode = 'en-us'
title = 'Lasse Medla Webpage'
[markup.highlight]
noclasses = false
style = "github" 
[[module.imports]]
path = "github.com/willfaught/paige"
[caches]
  [caches.images]
    dir = ':cacheDir/images'